# Generated by Django 4.0.4 on 2022-04-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_site_at', models.DateTimeField(auto_created=True, db_column='Added At', null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('publish_date', models.DateField(db_column='Published At', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('appropriate', models.CharField(choices=[('U8', 'under 8'), ('U15', '8-15'), ('+18', 'adults')], default='U8', max_length=3, null=True)),
                ('image', models.FileField(null=True, upload_to='book_list/static/book_list/images')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_list.author')),
            ],
        ),
    ]
