# Generated by Django 4.0.4 on 2022-04-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0002_alter_book_add_to_site_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='appropriate',
        ),
    ]
