# Generated by Django 4.0.4 on 2022-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0004_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='appropriate',
            field=models.CharField(choices=[('U8', 'under 8'), ('U15', '8-15'), ('+18', 'adults')], default='U8', max_length=3, null=True),
        ),
    ]
