# Generated by Django 4.0.4 on 2022-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0005_book_appropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, default='book_list/static/book_list/images/1.jpg', null=True, upload_to='book_list/static/book_list/images'),
        ),
    ]
